### ISSUE TITLE
Mac OS : bs4.FeatureNotFound

### ISSUE THREAD

**Issue by eshrh** [Utagai/spice#22]
Hey!

First off, I love this. Like, *I LOVE THIS*. So thanks! 

Anyway, running python 3.6, on mac os High Sierra, BeautifulSoup throws FeatureNotFound, full error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spice_api/spice.py", line 165, in search
    query_soup = BeautifulSoup(search_resp.text, 'lxml')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

Evidently, lxml is missing, and everything works once lxml is installed with `pip3 install lxml`. It would be nice if lxml was included as a dependency when installing the package. I see this was once an issue, and *seems to have been fixed in #19*, but for whatever reason(possibly platform?) doesn't work. **EDIT: somehow, setup.py doesn't include lxml?**

I totally get it if you don't have the time to do this ( or just feeling lazy), so i'm trying to figure it out at the moment with a possible PR coming!

Thanks!
eshanmind

**Comment by Utagai** [comment]
Hey! Wow, thanks! You're very kind! This project was really just for my personal gain for another project I had been working on, so it's always nice to see it get attention every now and then, as little as it is. Your approach to your contributions thus far have been stellar and very nice. I'm by no means an expert on anything related to this project (or possibly anything at all!), so it's nice to see such warm contributions.

Indeed, I recall 'fixing' this. It seems as if I was either unsuccessful, or somehow it vanished, perhaps through other merges that didn't include it. Either way, I notice that you've already begun taking a stab at this, so I'll let you continue. I'm of course prepared to accept your possible PR :).

Otherwise, I'll probably look at it myself. However, with a limited schedule as mine it may take some time.

**Comment by eshrh** [comment]
#23 pull request!
