### ISSUE TITLE
Issue with MediumList.extremes()

### ISSUE THREAD

**Issue by eshrh** [Utagai/spice#24]
hey!

this should be a quick fix: MediumList.extremes()'s low value will practically always be 0, since it considers all anime in the list, meaning even plan-to-watch-anime, which by default have a score of 0. 

My suggestion for this is to simply make extremes() consider only values in the `completed` list.

Thanks!

**Comment by Utagai** [comment]
Indeed, this should be quick. Thanks again for your help!

**Comment by eshrh** [comment]
noice 👌

**Comment by eshrh** [comment]
oops

**Comment by eshrh** [comment]
@Utagai shouldn't we not consider both plantowatch _and_ currently watching?

**Comment by Utagai** [comment]
@eshanmind What do you mean? I think the original suggestion of considering only completed makes the most sense. Planed to watch and currently watching are both risks since not everyone will assign scores to them. I know many people who give no scores to anime until they've finished it. I'm an exception, but this is not always the case.

In fact, I imagine the reason I didn't catch this issue is because I tested most of the code on myself. If anything, I think I'm in the minority of people who give a score reflecting his/her current opinion on the show!

**Comment by eshrh** [comment]
Good point; I usually don't give currently watching shows a rating, so that's probably why I thought of not considering completed. I only tested the code on myself too, so that's probably why I didn't think from another perspective!

I think this is good for close
