### ISSUE TITLE
Library should not store credentials internally

### ISSUE THREAD

**Issue by mlindner** [Utagai/spice#3]
API credentials are usually stored at the top level and are passed to every API call. This is especially confusing as you return the API credentials to the user and then also silently store them internally.

**Comment by Utagai** [comment]
Hm, gotcha. It's my first API and I didn't even realize that was the convention. Thanks so much for the critique, I'd have never known. 

By storing them at the top level, do you mean the user should be storing the credentials and passing them in manually?

**Comment by mlindner** [comment]
There's two ways, pass the API credentials to every call or maintain a connection object that stores the credentials that you call functions on. The idea is that functions shouldn't maintain or store state. Here's two examples of passing API credentials to REST APIs:
http://boto.cloudhackers.com/en/latest/s3_tut.html
http://twilio-python.readthedocs.io/en/latest/usage/phone-calls.html

**Comment by mlindner** [comment]
The primary thing is that this line shouldn't exist here anymore after the changes: https://github.com/Utagai/spice/blob/master/spice_api/spice.py#L104

**Comment by mlindner** [comment]
(BTW, unrelated, but for ease of programming on yourself when dealing with beautiful soup I usually do: from bs4 import BeautifulSoup as bs . This improves coding speed a bit when dealing with a bunch of soup stuff.)

**Comment by Utagai** [comment]
It makes a lot of sense to me about why functions should not be storing state. However, I'm kind of confused about your wording regarding connection objects: '_or maintain a connection object that stores the credentials that you call functions on._'

Doesn't that violate the principle of not storing state, since I'm still storing it but just in a different object? Unless connection objects are just holding references to something the user is holding? I checked out the boto thing and it seems like they are storing a _reference_ to the credentials, not the credentials themselves -- is this what you mean?

I do understand the actual problem, so that line will for sure be gone, but the question of how I should remove it remains. Right now I'm leaning towards this connection idea, assuming it is what I think (a reference to the credentials, not storing the credentials themselves).

Good idea about the BeautifulSoup thing, I've seen that in lots of snippets. Honestly, for me, I subscribe to the idea about clear naming. bs(html_data) is not that clear to someone who is just looking at a snippet of my code and hasn't seen the imports, and using the full name is just a slight burden to me, which I'm willing to take the hit for if it means people won't be confused. :)

**Comment by mlindner** [comment]
Objects are expected to store state just as variables are expected to store state. Functions that store state can be "functors" which are callable objects or rarely, which is what you have, "side-effecting functions", namely functions that have unseen side-effects. It is expected that objects will store state.

> Unless connection objects are just holding references to something the user is holding? I checked out the boto thing and it seems like they are storing a reference to the credentials, not the credentials themselves -- is this what you mean?

When you pass variables in to something in python in this situation copies are made. There are no references stored that point back to your original credentials. With the line `conn = S3Connection('<aws access key>', '<aws secret key>')` the credentials are copied into the "conn" object which is an instantiation of the S3Connection class. Link here: http://boto.cloudhackers.com/en/latest/ref/s3.html#boto.s3.connection.S3Connection

> I do understand the actual problem, so that line will for sure be gone, but the question of how I should remove it remains. Right now I'm leaning towards this connection idea, assuming it is what I think (a reference to the credentials, not storing the credentials themselves).

Hmm the credentials are actually stored. I'm not understanding why you would prefer a reference to the credentials as opposed to directly storing them. Here's a couple of example pieces of code re-worked from your example code that show how the API could work depending on how you write it (first two examples are the same, just showing the different calls):

`creds = spice.load_auth_from_file('auth')`
`search_results = spice.search('Spice and Wolf', spice.get_medium('anime'), creds)`
or
`creds = spice.init_auth(username, pw)`
`search_results = spice.search('Spice and Wolf', spice.get_medium('anime'), creds)`
or
`session = spice.new_session(username, pw)`
`search_results = session.search('Spice and Wolf', spice.get_medium('anime'))`
or
`anime_session = spice.new_anime_session(username, pw)`
`search_results = anime_session.search('Spice and Wolf')`
or
`anime_session = spice.new_session(username, pw, spice.get_medium('anime'))`
`search_results = anime_session.search('Spice and Wolf')`

**Comment by mlindner** [comment]
My personal preference is the 4th or 5th example.

**Comment by Utagai** [comment]
We're clear now, that second to last comment cleared up what you meant for me and I see the benefits. I am also leaning towards the 4th example, but also like the 1st/2nd examples. I'll mull it over and choose one of the three and implement it.

Thanks for your critique. This is my first API and I've already learned a lot from making it and from your suggestions. Expect a change sometime in the next week or so (I'm too busy to implement them immediately).

**Comment by mlindner** [comment]
Not exactly happy you picked the first two examples, but it'll have to do I guess. I guess I'll just wrap it in a functools.partial to get the usage I want.

**Comment by Utagai** [comment]
Yup, I'm busy so I just went for the simplest option. Shouldn't be too big of a deal and personally I think this makes more sense when looking at the interface.

Different strokes for different folks.
